---
name: RSFedAvg
init:
  _target_: rs_fedavg.FedAvgReproducibleSampling
  initial_parameters: null
  evaluate_metrics_aggregation_fn: wandb_utils.aggregate_weighted_average
  fit_metrics_aggregation_fn: wandb_utils.aggregate_weighted_average
  accept_failures: True
  seed: 1337
eta_l: 0.0001 # client's learning rate