---
# This generator is never used by default
# use it if you need to change the client
# get_client_generator:
#   _target_: project.client.client.get_client_generator

# Client fit config
fit_config:
  batch_size: 4
  epochs: 1
  learning_rate: 0.03

# Client eval config
eval_config:
  batch_size: 4

# The names of metrics you wish to aggregate
fit_metrics: [train_loss]
evaluate_metrics: [test_accuracy]
