---
# Federated setup
num_rounds: 1
num_total_clients: 10
num_clients_per_round: 2
num_evaluate_clients_per_round: 2

# If clients should be sampled with replacement
# when the dataset is not large enough
enable_resampling: false

# Client resources
cpus_per_client: 10
gpus_per_client: 1

# Seed for client selection
seed: 1337

# Configuration for the federated testing function
# fed_test_config:
  # batch_size: 32

# Settings for loading the initial parameters 
# used by the server
load_saved_parameters: false
parameters_folder: null

# If reusing an output directory for checkpointing
use_results_dir: false

# The round from which to load the parameters
# if null it will load the most recent round
parameters_round: null

# Configuration instructions for initial parameters
initial_parameters_config: {}
