---
name: cross-silo
num_total_clients: 100
lda_concentration: 0.10
num_train_clients_per_round: 10
num_eval_clients_per_round: 10
local_epochs: 10
lr: 0.001
batch_size: 32
local_eval: True
centralised_eval: True
evaluate_fn:
  _target_: test_fn.centralised_evaluate
test_loop:
  _target_: test_fn.test
