---
# Control wandb logging
use_wandb: true

wandb:
  mode: enabled
  setup:
    project: template
    tags: ['strategy_${strategy.name}', 'net_${client.network}', 'seed_${fed.seed}']
    entity: null
    mode: online
