---
defaults:
  - _self_
  - client: default
  - fed: default
  - strategy: fedavg

# Control wandb logging
use_wandb: true

# Wandb configuration
wandb:
  setup:
    project: template
    tags: ['strategy_${strategy.name}', 'seed_${fed.seed}']
    entity: null
    mode: online
